### PR TITLE
Add books list feature as example

### LINKED ISSUE #62: Implement redux structure
The idea is to implement a regular redux structure in this project, with a simple feature (a list of books) as an example.

To add:
- Actions
- Components
- Reducers
- Resources

Required by https://github.com/api-platform/demo/pull/55#discussion_r226182245

### PR DESCRIPTION
**Pull request by vincentchalamon**
Fix #62

This PR only implements a feature presenting a list of books (no delete/create/edit/show) as an example, using [`@api-platform/client-generator`](https://www.npmjs.com/package/@api-platform/client-generator).

The main theme remains the same as the welcome page (cf. Theme.js as template).

### CODE REVIEW

**Comment by dunglas** [comment]
The generator has been designed to be used with Bootstrap, maybe should we install it instead?

**Comment by vincentchalamon** [comment]
I redesigned the default books list according to the welcome template, to illustrate how to use a `Theme` in a react app.

**Comment by vincentchalamon** [comment]
If you want to update this theme using bootstrap, I think it should be in a separate PR

**Comment by dunglas** [comment]
Actually, Bootstrap should already be available: https://github.com/api-platform/api-platform/blob/master/client/package.json#L6-L7

This has been designed for this usage from the ground.

**Comment by vincentchalamon** [comment]
But revamping the demo theme using bootstrap should be out of this PR

**Pull request merged**
