### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by vincentchalamon**
- [x] Migrate to PHP 7.1-rc
- [x] Update composer download (from https://github.com/api-platform/api-platform/pull/162)

I need to upgrade to PHP 7.1 (even in rc) to use `?string` syntax to allow `null` value in typehint

### CODE REVIEW

**Comment by vincentchalamon** [comment]
This PR can also be updated from https://github.com/api-platform/api-platform/pull/162

**Comment by teohhanhui** [comment]
> I need to upgrade to PHP 7.1 (even in rc) to use ?string syntax to allow null value in typehint

That can be approximated in function parameters by

```php
string $xxx = null
```

Of course, there is no equivalent for return type. In which case, we just don't need to specify it yet.

**Comment by dunglas** [comment]
Can you remove the switch to 7.1 for now? We'll upgrade the distribution when it will be released.

**Comment by vincentchalamon** [comment]
@dunglas @teohhanhui ok so this PR is useless for now, but maybe it should be more interesting to move https://github.com/api-platform/api-platform/pull/162 in this repo

**Pull request closed without merging**
