### PR TITLE
Added installation instructions for #19

### PR DESCRIPTION
**Pull request by felicitus**
This PR fixes the missing installation instructions for #19

### CODE REVIEW

**Comment by meyerbaptiste** [comment]
What about `docker-compose up`? It's easier! 😄

**Comment by felicitus** [comment]
As I do not use docker, I cant provide instructions

**Comment by dunglas** [comment]
I agree with @meyerbaptiste, we can explain how to run the demo without Docker, but the recommended way is `docker-compose up` (also because the setup will become more complex when we'll add JS tools in the demo).

Can you just add a line recommending to run `docker-compose up`?

**Comment by dunglas** [comment]
Thanks @felicitus

**Pull request merged**
