### PR TITLE
Install & configure Mercure + Postgres PUB/SUB

### LINKED ISSUE #114: Install & configure Mercure + Postgres PUB/SUB
## API
- [x] Install symfony/messenger
- [x] Configure 2 connections: Postgres (Doctrine) & Mercure
- [x] Create Book::generateCover custom item operation
- [x] Send a message on Postgres connection on Book::generateCover operation
- [x] Consume this message which generates a cover (use a library which generates a big random image, this must use a lot of resources to check the performances)
- [x] Send the cover image on the Mercure connection
- [x] Add Behat tests

## Client
- [x] Connect to Mercure
- [x] Display Book cover
- [x] Add e2e tests

### PR DESCRIPTION
**Pull request by vincentchalamon**
Fix #114

- [x] Use [PASS](https://api.imgflip.com) to generate image
- [x] Update docker-compose version in travis-ci (require to handle `-e` option in `docker-compose exec`)
- [x] Update PHP version in Dockerfile (cf. https://github.com/symfony/symfony/issues/32395)
- [x] Update Symfony components to 4.3.3
- [x] Update api-platform/core to 2.4.6
- [x] Update all dependencies

### CODE REVIEW

**Comment by teohhanhui** [comment]
> api-platform/core to dev-master (required to install symfony/messenger:4.3)

Not anymore.

**Comment by soyuka** [comment]
I did a `docker-compose build` and a `docker-compose up` locally but I end up having this error:

```
admin_1        | Failed to compile.
admin_1        |
admin_1        | ./src/App.js
admin_1        | Module not found: Can't resolve '@api-platform/admin' in '/usr/src/admin/
```

Other containers are working fine. I think that there's an issue while linking admin's `node_modules` (it needs further investigation)

**Comment by vincentchalamon** [comment]
@soyuka No problem on my side using a fresh instance of the current branch:
```
Attaching to demo_admin_1
admin_1        | yarn run v1.12.3
admin_1        | $ react-scripts start
admin_1        | Starting the development server...
admin_1        | 
admin_1        | Compiled successfully!
admin_1        | 
admin_1        | You can now view admin in the browser.
admin_1        | 
admin_1        |   Local:            http://localhost:3000/
admin_1        |   On Your Network:  http://172.18.0.6:3000/
admin_1        | 
admin_1        | Note that the development build is not optimized.
admin_1        | To create a production build, use yarn build.
```

Can you try again?

**Comment by soyuka** [comment]
I had to invalidate my volume:

```
docker-compose down -v
```

Now everything is okay on my end!

**Comment by soyuka** [comment]
Nevermind still an error:

```
php_1          | !!  Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, unexpected 'if' (T_IF), expecting variable (T_VARIABLE) or '{' or '$' in /srv/api/vendor/doctrine/doctrine-migrations-bundle/DependencyInjection/Configuration.php:61
php_1          | !!  Stack trace:
php_1          | !!  #0 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('Doctrine\\Bundle...')
php_1          | !!  #1 [internal function]: spl_autoload_call('Doctrine\\Bundle...')
php_1          | !!  #2 /srv/api/vendor/symfony/config/Resource/ClassExistenceResource.php(78): class_exists('Doctrine\\Bundle...')
php_1          | !!  #3 /srv/api/vendor/symfony/dependency-injection/ContainerBuilder.php(353): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
php_1          | !!  #4 /srv/api/vendor/symfony/dependency-injection/Extension/Extension.php(84): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('Doctrine\\Bundle...')
php_1          | !!  #5 /srv/api/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(68): Symfony\Component\DependencyInjection\Extension\Extension->getConfiguration in /srv/api/vendor/doctrine/doctrine-migrations-bundle/DependencyInjection/Configuration.php on line 61
p
```

**Comment by vincentchalamon** [comment]
@dunglas Any news about this one?

**Pull request merged**
